name: Build Android

on:
  push:
    paths:
      - '**.dart'
      - '**.yaml'
      - 'android/**'

jobs:
  build_android:
    name: Build Android
    uses: apivideo/.github/.github/workflows/flutter_build_android.yml@main
    with:
      cache: true
